version: '3.7'
services:
  hapea:
    image: server-hapea
    container_name: hapea
    build:
      context: ./
      dockerfile: Dockerfile
    # volumes:
    #   - ./files/:/home/user1/files/ # map current directory ./api to container path, will act as live code
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - backend
  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
networks:
  backend:

volumes:
  cache:
    driver: local