version: '3.7'
services:
  hapea:
    image: server-hapea
    container_name: hapea
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt/:rw
    restart: unless-stopped
    networks:
      - backend
networks:
  backend:

volumes:
  cache:
    driver: local